/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mohamed_muaaz' at '7/27/21 11:13 AM' with Gradle 2.11
 *
 * @author mohamed_muaaz, @date 7/27/21 11:13 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
